name: Call Reusable Build

on:
 # push:
   # branches:
  #    - main
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/reuseable_build.yml

    with:
      app_name: "my-web-app"
      environment: "production"

    secrets: inherit
    

  show-version:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Show build version
        run: |
          echo "Build version received from reusable workflow:"
          echo "${{ needs.build.outputs.build_version }}"