name: Python Matrix

on:
  push:

jobs:
  test-python:
    strategy:
      matrix:
        os: ['ubunta-latest','windows-latest']

    strategy:
      matrix:
            python-versions: ['3.12','3.13','3.14']
     runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version
