name: Secret Environment Variables

on:
  push:

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Docker credentials
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          if [ -n "$DOCKER_USERNAME" ]; then
            echo "Docker username is set: true"
          else
            echo "Docker username is set: false"
          fi

    